name: Threagile Security Analysis

on:
  push:
    branches:
      - main

jobs:
  threagile-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go (required for Threagile)
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install Threagile
        run: |
          go install github.com/threagile/threagile@latest

      - name: Navigate to Repository Directory
        run: cd $GITHUB_WORKSPACE  # Ensure you're in the repository root

      - name: List Directory Contents
        run: ls -l  # Check the contents to verify the presence of Threagile.yaml

      - name: Run Threagile Analysis
        run: threagile Threagile.yaml

      - name: Archive Threagile Reports
        uses: actions/upload-artifact@v2
        with:
          name: threagile-reports
          path: threagile_reports  # Update this path according to your report directory
