name: Threagile Security Analysis

on:
 push:
    branches:
      - main

jobs:
 threagile-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go (required for Threagile)
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Run Threagile Analysis
        id: threagile
        uses: threagile/run-threagile-action@v1
        with:
          model-file: 'threagile2.yaml'

      - name: Archive Threagile Reports
        uses: actions/upload-artifact@v2
        with:
          name: threagile-reports
          path: threagile_reports # Update this path according to your report directory