name: Threagile Security Analysis

on:
  push:
    branches:
      - main

jobs:
  threagile-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go (required for Threagile)
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

    #   - name: List Directory Contents
    #     run: |
    #       ls -l
    #       ls -l /github/workspace  # Explicitly list contents of the workspace directory

      - name: Change Directory
        run: cd /Threagile_test  # Change to the workspace directory

      - name: Run Threagile Analysis
        run: threagile Threagile.yaml  # Provide full path to the Threagile.yaml file

      - name: Archive Threagile Reports
        uses: actions/upload-artifact@v2
        with:
          name: threagile-reports
          path: threagile_reports  # Update this path according to your report directory
